In [1]:
#### Problem definition.

In [2]:
import numpy as np

In [32]:
s_i = np.array([[1,3,5],[2,0,6],[4,8,7]])
print('s_i\n', s_i)

s_f = np.array([[1,2,3],[4,5,6],[7,8,0]])
print('s_f\n', s_f)

x = np.argwhere(s_i == 0)
print(x)

s_i
 [[1 3 5]
 [2 0 6]
 [4 8 7]]
s_f
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
[[1 1]]


In [44]:

def possible_actions(s):
    x = np.argwhere(s == 0)
    actions = []
    if x[0,0]-1>=0:
        actions.append('up')
    if x[0,0]+1<=2:
        actions.append('down')
    if x[0,1]-1>=0:
        actions.append('left')
    if x[0,1]+1<=2:
        actions.append('right')
    return actions

def new_state(s,a):
    x = np.argwhere(s == 0)
    s_out = s.copy()

    if a == 'up':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0]+1, x[0,1]]
        s_out[x[0,0]+1, x[0,1]]=0
    
    if a == 'down':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0]-1, x[0,1]]
        s_out[x[0,0]-1, x[0,1]]=0
    
    if a == 'left':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0], x[0,1]-1]
        s_out[x[0,0], x[0,1]-1]=0
     
    if a == 'right':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0], x[0,1]+1]
        s_out[x[0,0], x[0,1]+1]=0
        
    return s_out
        

In [45]:
####prueba 
s_i = np.array([[1,3,5],[2,0,6],[4,8,7]])
print('s_i\n', s_i)
print(new_state(s_i,'right'))

s_i
 [[1 3 5]
 [2 0 6]
 [4 8 7]]
[[1 3 5]
 [2 6 0]
 [4 8 7]]


In [60]:
class Node(): 
    def __init__(self, dad ,state):
        self.dad = dad
        self.state = state
        n = Node(None, s_i)
        n1 = Node(n.state, s_1)
        if (np.array_equal(n.state, n1.state)== True):
            print('fin')
    
    
    
        
        

In [72]:
from collections import deque
dq = dequeleft(['b','c','d'])
print (dq)

NameError: name 'dequeleft' is not defined

In [ ]:
print(Node.)

In [71]:
lis = [5,2,3]
lis.popleft()
print(lis)

AttributeError: 'list' object has no attribute 'popleft'