In [4]:
# 8Puzle

In [7]:
import numpy as np
from collections import deque

In [8]:
s_i = np.array([[1,3,6],[7,8,4],[5,0,2]])
print('s_i\n', s_i)

s_f = np.array([[1,2,3],[4,5,6],[7,8,0]])
print('s_f\n', s_f)




s_i
 [[1 3 6]
 [7 8 4]
 [5 0 2]]
s_f
 [[1 2 3]
 [4 5 6]
 [7 8 0]]


In [34]:

def possible_actions(s):
    x = np.argwhere(s == 0)
    
    actions = []
    
    if x[0,0]-1>=0:
        actions.append('down')
        
    if x[0,0]+1<=2:
        actions.append('up')
        
    if x[0,1]-1>=0:
        actions.append('right')
        
    if x[0,1]+1<=2:
        actions.append('left')
    return actions

def new_state(s,a):
    
    x = np.argwhere(s == 0)
    s_out = s.copy()

    if a == 'up':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0]+1, x[0,1]]
        s_out[x[0,0]+1, x[0,1]]=0
    
    if a == 'down':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0]-1, x[0,1]]
        s_out[x[0,0]-1, x[0,1]]=0
    
    if a == 'right':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0], x[0,1]-1]
        s_out[x[0,0], x[0,1]-1]=0
     
    if a == 'left':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0], x[0,1]+1]
        s_out[x[0,0], x[0,1]+1]=0
        
    return s_out


def is_child_in_explored(child, explorado):
    for state in explorado: 
        if (np.array_equal(child,state)==True):
            return True
        return False           
        
def is_child_in_frontier(child,fronter): ##si el nuño esta en la frontera
    for node in fronter:
        if (np.array_equal(child,node.state)==True):
            return True
    return False

def cost_action(action):
    if (action == 'down'):
        cost = 1
        return cost
    
    if (action == 'up'):
        cost = 2
        return cost
        
    if (action == 'right'):
        cost = 1
        return cost

    if (action == 'left'):
        cost = 2
        return cost
class Node(): 
    def __init__(self, dad ,state, action, cost):
        self.dad = dad #atributos clase
        self.state = state
        self.action = action
        self.cost = cost
    
    def __lt__(self, other):
        return self.cost.__lt__(other.cost)
    def __gt__(self, other):
        return self.cost.__gt__(other.cost)
    def __eq__(self, other):
        return self.cost.__eq__(other.cost)

        

In [4]:
def bfs():
    node_1 = Node(None,s_i, None)
       
    fronter = deque()
    fronter.append(node_1)
    
    explorado = []
    final_child = None
   
    while(True): 
        if len(fronter)==0: #conjunto de la frontera Vacia.
            print('failure')
            break
    
        else:
            node_1 = fronter.popleft() #FIFO nodo mas superficial de la frontera.
            explorado.append(node_1.state) #agregar el nodo de explorado a los explorados.
        solution =False    
        for action in possible_actions(node_1.state):
            child = Node(node_1, new_state(node_1.state, action), action)
            
            if (is_child_in_explored(child.state, explorado)==False and is_child_in_frontier(child.state,fronter)==False):
                if (np.array_equal(child.state,s_f)==True):
                    print("solucion encontrada")
                    solution = True
                    final_child = child
                    break
                fronter.append(child)
        if (solution == True):
            break
   
    
    print("pasos")   
    node_aux = final_child
    sol_actions  = []
    while(node_aux.action != None):
        sol_actions.append(node_aux.action)
        node_aux = node_aux.dad
        
    return print(list(reversed(sol_actions)))

In [23]:
bfs()

solucion encontrada
pasos
['down', 'left', 'up', 'right', 'right', 'down', 'left', 'left', 'down', 'right', 'up', 'up', 'left']


In [24]:
def dfs():
    node_1 = Node(None,s_i, None)
       
    fronter = deque()
    fronter.appendleft(node_1)
    
    explorado = []
    final_child = None
   
    while(True): 
        if len(fronter)==0: #conjunto de la frontera Vacia.
            print('failure')
            break
    
        else:
            node_1 = fronter.popleft() #FIFO nodo mas superficial de la frontera.
            explorado.append(node_1.state) #agregar el nodo de explorado a los explorados.
        solution =False    
        for action in possible_actions(node_1.state):
            child = Node(node_1, new_state(node_1.state, action), action)
            
            if (is_child_in_explored(child.state, explorado)==False and is_child_in_frontier(child.state,fronter)==False):
                if (np.array_equal(child.state,s_f)==True):
                    solution = True
                    final_child = child
                    break
                fronter.appendleft(child)
        if (solution == True):
            break
   
    
       
    node_aux = final_child
    sol_actions  = []
    while(node_aux.action != None):
        sol_actions.append(node_aux.action)
        node_aux = node_aux.dad
        
    return print(list(reversed(sol_actions)))

In [ ]:
dfs()

In [24]:
def ucs():
    node_1 = Node(None,s_i, None, None)
       
    fronter = []
    fronter.append(node_1)
    
    explorado = []
    final_child = None
   
    while(True): 
        if len(fronter)==0: #conjunto de la frontera Vacia.
            print('failure')
            break
    
        else:
            node_1 = fronter.pop(0)
            explorado.append(node_1.state) #agregar el nodo de explorado a los explorados.
        solution =False    
        for action in possible_actions(node_1.state):
            child = Node(node_1, new_state(node_1.state, action), action, cost_action(action))
            
            if (is_child_in_explored(child.state, explorado)==False and is_child_in_frontier(child.state,fronter)==False):
                if (np.array_equal(child.state,s_f)==True):
                    solution = True
                    final_child = child
                    break
                fronter.append(child)
        fronter= sorted(fronter)
        
        if (solution == True):
            break
   
    
       
    node_aux = final_child
    sol_actions  = []
    while(node_aux.action != None):
        sol_actions.append(node_aux.action)
        node_aux = node_aux.dad
        
    return print(list(reversed(sol_actions)))

In [35]:
ucs()

['down', 'left', 'up', 'right', 'right', 'down', 'left', 'left', 'down', 'right', 'up', 'up', 'left']
