In [ ]:
#### Problem definition.

In [1]:
import numpy as np

In [54]:
s_i = np.array([[1,3,5],[0,2,6],[4,8,7]])
print('s_i\n', s_i)

s_f = np.array([[1,2,3],[4,5,6],[7,8,0]])
print('s_f\n', s_f)

s_i
 [[1 3 5]
 [0 2 6]
 [4 8 7]]
s_f
 [[1 2 3]
 [4 5 6]
 [7 8 0]]


In [55]:
x = np.argwhere(s_i == 0)



In [49]:

#UP
if x[0,0]-1>=0:
    s_i[1,0] = s_i[2,0]
    s_i[2,0]=0
    print(s_i)




[[1 3 5]
 [4 2 6]
 [0 8 7]]


In [53]:
#down
if x[0,0]+1<=2:
    s_i[1,0] = s_i[0,0]
    s_i[0,0]=0
    print(s_i)

[[0 3 5]
 [1 2 6]
 [4 8 7]]


In [56]:
#right
if x[0,1]+1<=2:
    s_i[1,0] = s_i[1,1]
    s_i[1,1]=0
    print(s_i)    
        

[[1 3 5]
 [2 0 6]
 [4 8 7]]


In [34]:
actions = ['up', 'down', 'left', 'right']

class puzle: 
    def possible_actions(s):
        if x[0,0]-1>=0:
            print('up')
        if x[0,0]+1<=2:
            print('down')  
        if x[0,1]-1>=0:
            print('left')
        if x[0,1]+1<=2:
            print('right')
        return possible_actions

    def new_state(s,a):
        pass

In [35]:
print(puzle.possible_actions(s_i))

up
down
left
right
<function possible_actions at 0x000000AF5CEC7268>
