In [4]:
# 8Puzle

In [39]:
import numpy as np
from collections import deque

In [58]:
s_i = np.array([[1,2,3],[4,5,6],[7,8,0]])
print('s_i\n', s_i)

s_f = np.array([[1,2,3],[4,5,6],[7,0,8]])
print('s_f\n', s_f)




s_i
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
s_f
 [[1 2 3]
 [4 5 6]
 [7 0 8]]


In [59]:

def possible_actions(s):
    x = np.argwhere(s == 0)
    
    actions = []
    
    if x[0,0]-1>=0:
        actions.append('down')
        
    if x[0,0]+1<=2:
        actions.append('up')
        
    if x[0,1]-1>=0:
        actions.append('right')
        
    if x[0,1]+1<=2:
        actions.append('left')
    return actions

def new_state(s,a):
    
    x = np.argwhere(s == 0)
    s_out = s.copy()

    if a == 'up':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0]+1, x[0,1]]
        s_out[x[0,0]+1, x[0,1]]=0
    
    if a == 'down':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0]-1, x[0,1]]
        s_out[x[0,0]-1, x[0,1]]=0
    
    if a == 'right':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0], x[0,1]-1]
        s_out[x[0,0], x[0,1]-1]=0
     
    if a == 'left':
        s_out[x[0,0], x[0,1]] = s_out[x[0,0], x[0,1]+1]
        s_out[x[0,0], x[0,1]+1]=0
        
    return s_out


def is_child_in_explored(child, explorado):
    for state in explorado: 
        if (np.array_equal(child,state)==True):
            return True
        return False           
        
def is_child_in_frontier(child,fronter):
    for node in fronter:
        if (np.array_equal(child,node.state)==True):
            return True
    return False



class Node(): 
    def __init__(self, dad ,state, action):
        self.dad = dad #atributos clase
        self.state = state
        self.action = action

In [60]:
def bfs():
    node_1 = Node(None,s_i, None)
       
    fronter = deque()
    fronter.append(node_1)
    
    explorado = []
    final_child = None
   
    while(True): 
        if len(fronter)==0: #conjunto de la frontera Vacia.
            print('failure')
            break
    
        else:
            node_1 = fronter.popleft() #FIFO nodo mas superficial de la frontera.
            explorado.append(node_1.state) #agregar el nodo de explorado a los explorados.
        solution =False    
        for action in possible_actions(node_1.state):
            child = Node(node_1, new_state(node_1.state, action), action)
            
            if (is_child_in_explored(child.state, explorado)==False and is_child_in_frontier(child.state,fronter)==False):
                if (np.array_equal(child.state,s_f)==True):
                    solution = True
                    final_child = child
                    break
                fronter.append(child)
        if (solution == True):
            break
   
    
       
    node_aux = final_child
    sol_actions  = []
    while(node_aux.action != None):
        sol_actions.append(node_aux.action)
        node_aux = node_aux.dad
        
    return print(list(reversed(sol_actions)))

In [61]:
bfs()

['right']
